# Generated by Django 3.0.11 on 2020-11-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='is_employee'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='is_employer'),
        ),
    ]
